import type { Metadata } from "next";
import styles from "@/app/(auth)/layout.module.scss";
import Image from "next/image";
import authImg from "@/assets/imgs/socials/auth.jpg";
import { headers } from "next/headers";
export const metadata: Metadata = {
  title: "SieuBuong",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <div className={styles["auth-container"]}>
        <div className={styles["formSide"]}>{children}</div>
        <div className={styles["imageSide"]}>
          <Image src={authImg} alt="" />
        </div>
      </div>
    </div>
  );
}
